[project]
name = "chrome-dino-bot"
version = "0.1.0"
description = "Chrome Dino Bot using Opencv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mss>=10.1.0",
    "opencv-python>=4.12.0.88",
    "pyautogui>=0.9.54",
    "pynput>=1.8.1",
]
